services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command: --config.file=/config/prometheus.yml
    ports:
    #--- Prometheus Default Port ---
      - "9090:9090"
    volumes:
      - /etc/prometheus:/config
      - prometheus:/prometheus
    networks:
      - your_network_name

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
    #--- Grafana Default Port ---
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - your_network_name

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command: --path.rootfs=/host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - your_network_name

volumes:
  prometheus:
  grafana:

networks:
  your_network_name:
    external: true
